version: '3.8'

services:
  betting-scraper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SCRAPE_INTERVAL=300
      - MAX_CONCURRENT_SCRAPERS=3
      - REQUEST_TIMEOUT=30
      - CHROME_HEADLESS=true
      - CHROME_DISABLE_GPU=true
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: Add monitoring with Prometheus (uncomment if needed)
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: unless-stopped

volumes:
  logs:
  # redis_data: